version: "3.8"
services:
  app:
    build:
      context: .
    command: sleep infinity
    volumes:
      - .:/workspace/
      - static_data:/vol/web
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DJANGO_ENV=development

      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=127.0.0.1,localhost

      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com

      - REDIS_HOST=redis://redis:6379/1
      - REDIS_KEY_PREFIX=pillar

      - DATABASE_NAME=db
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

      - EMAIL_USE_TLS=true
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  static_data:
  redis_data:
  postgres_data:
